/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.64
 * Generated at: 2016-04-15 03:16:23 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.login;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;
import com.linkage.bace.core.GlobalValues;
import com.asiainfo.portal.framework.busiclient.BusiSSOFilter;
import com.asiainfo.portal.framework.busiclient.DefaultPopedomImpl;
import com.asiainfo.os.InitParam;

public final class ssoLogin_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

	response.setHeader("Pragma","No-cache");
	response.setHeader("Cache-Control","no-cache");
	response.setHeader("Cache-Control","no-store");
	response.setDateHeader("Expires", 0);
	String contextPath = request.getContextPath();
	String basePath = request.getRequestURL().toString();
	basePath = basePath.substring(0, basePath.indexOf(contextPath) + contextPath.length()+1);

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("\t<title>欢迎登录大数据辅助突发公共事件防控平台</title>\r\n");
      out.write("\t<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\"/>\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"");
      out.print(GlobalValues.CONTENT_PATH);
      out.write("/login/login.css\">\r\n");
      out.write("\t<script src=\"");
      out.print(GlobalValues.CONTENT_PATH);
      out.write("/common/js/jquery/jquery-1.11.3.min.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"");
      out.print(GlobalValues.CONTENT_PATH);
      out.write("/common/js/base.js\"></script>\r\n");
      out.write("\t<script src=\"");
      out.print(GlobalValues.CONTENT_PATH);
      out.write("/common/js/base.js\"></script>\r\n");
      out.write("\t<script src=\"");
      out.print(GlobalValues.CONTENT_PATH);
      out.write("/login/login.js\"></script>\r\n");
      out.write("\t\r\n");
      out.write("\t<script>\r\n");
      out.write("\t\tvar CONTENT_PATH = '");
      out.print(GlobalValues.CONTENT_PATH);
      out.write("';\r\n");
      out.write("\t</script>\r\n");
      out.write("\t\r\n");
      out.write("\t<style type=\"text/css\">\r\n");
      out.write("\t\tbody {\r\n");
      out.write("\t\t\tmargin-left: 0px;\r\n");
      out.write("\t\t\tmargin-top: 0px;\r\n");
      out.write("\t\t\tmargin-right: 0px;\r\n");
      out.write("\t\t\tmargin-bottom: 0px;\r\n");
      out.write("\t\t\tfont-size:12px; font-family:\"微软雅黑\"; color:#7d7d7d;\r\n");
      out.write("\t\t\toverflow:hidden;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t.top_login{ margin:0px auto; padding:0px; clear:both; height:70px;}\r\n");
      out.write("\t\t.top_login span{ float:right; padding:36px 10px 10px 0px;}\r\n");
      out.write("\t\t.foot_login{ width:55%; height:36px; line-height:36px; text-align:right;float:left;}\r\n");
      out.write("\t\t.foot_login2{  width:25%; height:36px; line-height:36px; text-align:left;float:left;;color:#0092C3;}\r\n");
      out.write("\t\t.content_login{ clear:both; height:420px; background:url(");
      out.print(GlobalValues.CONTENT_PATH);
      out.write("/login/images_login/bg_con.png) bottom center #32b5cb no-repeat;}\r\n");
      out.write("\t\t.formlogin{ float:right; margin:40px 40px 20px 30px; background:#ebf8fa; border-radius:5px; width:380px; height:320px;}\r\n");
      out.write("\t\t.botton_login{ background:url(");
      out.print(GlobalValues.CONTENT_PATH);
      out.write("/login/images_login/botton_login.png) no-repeat; width:136px; height:53px; border:0px; margin:0px; padding:0px;cursor:pointer;}\r\n");
      out.write("\t\t.listlogin{ margin:0px; padding:0px 20px; list-style:none;}\r\n");
      out.write("\t\t.listlogin li{ list-style:none; padding:16px 0px;}\r\n");
      out.write("\t\t.input_text{ border:#b5b5b5 solid 1px; width:90%; background:#ebf8fa; border-radius:5px; padding:14px 10px; font-family:\"微软雅黑\"; color:#5c5c5c;}\r\n");
      out.write("\t\t.login-tip{color:red; display:inline-block;}\r\n");
      out.write("\t</style>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\t<!--头部开始-->\r\n");
      out.write("\t<div class=\"top_login\"><span><img src=\"");
      out.print(GlobalValues.CONTENT_PATH);
      out.write("/login/images_login/icon.png\" align=\"absmiddle\" /> <label id=\"time\">2015/04/13  09:52</label></span><img style=\"height:70px\" src=\"");
      out.print(GlobalValues.CONTENT_PATH);
      out.write("/login/images_login/deploy/");
      out.print(InitParam.DEPLOY_PROVINCE);
      out.write("/logo.png\" /></div>\r\n");
      out.write("\t<!--头部结束-->\r\n");
      out.write("\t<!--内容开始-->\r\n");
      out.write("\t<div class=\"content_login\">\r\n");
      out.write("\t<div class=\"formlogin\"><div align=\"center\"><img src=\"");
      out.print(GlobalValues.CONTENT_PATH);
      out.write("/login/images_login/title_login.png\" /></div>\r\n");
      out.write("\t<ul class=\"listlogin\">\r\n");
      out.write("\t");

	String ssoHomePage = BusiSSOFilter.getSsoHomePage();
	boolean ssoStatus = DefaultPopedomImpl.getSsoStatus(request);
	//本地测试时放开，走本系统登录
	//ssoStatus = false;
	//boolean ssoStatus = false;
	if (ssoStatus){// 显示iframe代码
	
      out.write("\r\n");
      out.write("\t<iframe src=\"");
      out.print(ssoHomePage);
      out.write("/web3/jsp/local/zhejiang/login.jsp?redirectUrl=");
      out.print(java.net.URLEncoder.encode("http://10.78.235.26:31772/login/sso2main.jsp","GBK"));
      out.write("&resKey=26\"  \r\n");
      out.write("\t");
      out.write("\r\n");
      out.write("\t\t\twidth=\"380px\" height=\"253px\" frameborder=\"0\" scrolling=\"no\" style=\"left:150\" allowTransparency=\"true\" ></iframe>\r\n");
      out.write("\t");

	} else {//显示原登录方式
	
      out.write("\r\n");
      out.write("\t<li><input id=\"userId\" type=\"text\" class=\"input_text\" placeholder=\"请输入用户名\" value=\"\"/>\r\n");
      out.write("\t</li>\r\n");
      out.write("\t<li><input id=\"userPassword\" type=\"password\" class=\"input_text\" placeholder=\"请输入密码\" value=\"\"/>\r\n");
      out.write("\t</li>\r\n");
      out.write("\t<li><input id=\"loginBtn\" name=\"\" type=\"submit\" class=\"botton_login\" value=\"\" onclick=\"login(this)\"/>\r\n");
      out.write("\t\t<div class=\"login-tip\" id=\"loginTip\"></div>\r\n");
      out.write("\t</li>\r\n");
      out.write("\t");

	}
	
      out.write("\r\n");
      out.write("\t</ul>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!--内容结束-->\r\n");
      out.write("\t<!--底部开始-->\r\n");
      out.write("\t<div class=\"foot_login\">");
      out.print(InitParam.COPY_RIGHT);
      out.write("</div>\r\n");
      out.write("\t<div class=\"foot_login2\">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;建议使用IE9以上版本浏览器</div>\r\n");
      out.write("\t<!--底部结束-->\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("<script>\r\n");
      out.write("var _o = $(\"#time\");\r\n");
      out.write("setInterval(function(){\r\n");
      out.write("\tvar realdate = new Date().format(\"yyyy-MM-dd hh:mm:ss\")+'&nbsp;&nbsp;星期'+'日一二三四五六'.charAt(new Date().getDay());\r\n");
      out.write("\t_o.html(realdate);\r\n");
      out.write("},1);\r\n");
      out.write("</script>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
