/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.64
 * Generated at: 2016-04-15 03:04:06 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.common.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.asiainfo.os.InitParam;
import java.util.*;
import com.linkage.bace.core.GlobalValues;
import com.asiainfo.os.LogDSUtil;
import com.asiainfo.os.SessionInfoUtil;
import com.asiainfo.os.bean.StaffSessBean;
import com.asiainfo.portal.framework.busiclient.HttpPost;
import com.asiainfo.portal.framework.busiclient.SsoDataFetch;
import com.asiainfo.portal.framework.busiclient.DefaultPopedomImpl;
import com.asiainfo.login.LoginUtil;

public final class logout_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

	String loginUrl = GlobalValues.CONTENT_PATH + "/login/ssoLogin.jsp";

	//记录登录日志
	StaffSessBean staffSessBean = SessionInfoUtil
			.getStaffSessBean(session);
	if (null != staffSessBean) {
		String logContent = "退出";
		String funcId = "loginOut";
		String logType = "visit";
		LogDSUtil logDSUtil = new LogDSUtil();
		logDSUtil.insertVisitLog(staffSessBean, logContent, funcId);

		//本地session注销
		SessionInfoUtil.removeStaffSessBean(session);
	}

	//正式环境可能需要注销4A
	/* if (InitParam.DEPLOY_TYPE_PRODUCT.equals(InitParam.DEPLOY_TYPE)
			&& "zj".equals(InitParam.DEPLOY_PROVINCE)) {
		loginUrl = GlobalValues.CONTENT_PATH + "/login/ssoLogin.jsp";

		//4A session注销
		String hostIp = SsoDataFetch.getHostIp(request);
		String port = SsoDataFetch.getPort(request);
		String sessionId = SsoDataFetch.getMainSessionId(request);

		if (null != sessionId && sessionId.length() > 0) {
			LoginUtil.logOut(hostIp, port, sessionId);
		}
	} */

      out.write("\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("\tvar loginUrl = '");
      out.print(loginUrl);
      out.write("';\r\n");
      out.write("\twindow.top.location.href = loginUrl;\r\n");
      out.write("</script>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
